CONNECT scott/tiger;
SELECT DISTINCT JOB 
FROM EMP;
SELECT * FROM EMP;
SELECT * FROM DEPT; -- Ensure the EMP table exists and is accessible
DESCRIBE EMP;
SELECT emp.*, sal *12 as annual_salary FROM emp; -- Ensure the EMP table exists and is accessible
SELECT max(sal) 
FROM emp 
WHERE sal < 
(SELECT MAX(sal) 
 FROM emp 
 WHERE deptno = 
(SELECT DEPTNO 
 FROM DEPT 
 WHERE DNAME = 'SALES'));
SELECT table_name
FROM user_tables ;
SELECT sal - (sal*0.1) AS new_sal
FROM emp;
SELECT ename,sal*12 AS annual_salary
FROM emp;
SELECT ename,job, sal*6 as half_team_sal
from emp;
SELECT emp.*,sal*12+2000
from emp;
SELECT ename,sal,sal+(sal*0.1)
from emp;
SELECT DISTINCT SAL,COMM 
FROM EMP;
SELECT ename, sal, sal * 12 *0.928 AS annual_salary
FROM emp;
SELECT ename, sal, sal * 0.75 AS annual_salary
FROM emp;
SELECT ename,sal
FROM emp
WHERE sal < 1000;
SELECT ename,job
FROM emp
WHERE job ='SALESMAN';
SELECT * FROM emp
WHERE ENAME ='MILLER';
SELECT * FROM emp
WHERE HIREDATE >'31-DEC-1985';
SELECT ename,sal,sal*12 AS annual_salary
FROM emp
WHERE sal *12 > 12000;
SELECT ename,HIREDATE
FROM EMP
WHERE HIREDATE<='31-Dec-1981';
SELECT HIREDATE,ename,job
FROM emp
WHERE JOB='MANAGER';
SELECT * FROM emp
WHERE JOB = 'SALESMAN' 
  AND DEPTNO = 30 
  AND SAL > 800 
  AND SAL < 6000 
  AND HIREDATE > '31-DEC-1987'
  AND HIREDATE < '01-JAN-1990' 
  AND COMM > 100;
  SELECT * FROM EMP
  WHERE NOT SAL = 800;
  SELECT EMP.*,SAL *12 FROM EMP
  WHERE DEPTNO = 30 AND JOB = 'SALESMAN'
  AND SAL * 12 > 14000;
  SELECT ENAME, DEPTNO FROM EMP
  WHERE NOT DEPTNO IN (30, 20);
  SELECT ENAME,DEPTNO
  FROM EMP
  WHERE DEPTNO IN (10,30);
    SELECT ENAME,SAL 
    FROM EMP
    WHERE SAL NOT BETWEEN 4999 AND 7999;
    SELECT ENAME, SAL, COMM,HIREDATE
    FROM EMP
    WHERE HIREDATE BETWEEN '01-JAN-1981' AND '31-DEC-1988'AND COMM IS NOT NULL;
    SELECT ENAME, SAL
    FROM EMP
    WHERE ENAME LIKE '__L%R';
    SELECT ENAME, SAL,HIREDATE
    FROM EMP
    WHERE HIREDATE LIKE'01%';
    SELECT COUNT(ENAME)
    FROM EMP
    WHERE JOB='SALESMAN';
    SELECT AVG(SAL),COUNT(*)
    FROM EMP;
    SELECT COUNT(*)
    FROM EMP
    WHERE JOB IN ('CLERK', 'MANAGER');
    SELECT COUNT(*)
    FROM EMP
    WHERE DEPTNO IN (20,30) AND ENAME LIKE '%A%';
    SELECT AVG(SAL),MAX(SAL),SUM(SAL),COUNT(*)
    FROM EMP
    WHERE JOB IN ('PRESIDENT');
    SELECT COUNT(*) , deptno,JOB
    FROM emp
    GROUP BY ;
    SELECT MAX(SAL), DEPTNO
    FROM EMP
    WHERE SAL > 1500
    GROUP BY DEPTNO;
    SELECT DEPTNO, COUNT(JOB)
    FROM EMP
    WHERE JOB IN ('SALESMAN')
    GROUP BY DEPTNO;
    SELECT DEPTNO,JOB,SAL, COUNT(*)
    FROM EMP
    WHERE JOB NOT IN ('PRESIDENT')
    GROUP BY DEPTNO , JOB,SAL;
    SELECT DEPTNO, COUNT(*)
    FROM EMP
    WHERE JOB IN ('MANAGER')
    GROUP BY DEPTNO;
    SELECT DEPTNO, COUNT(*),SUM(SAL),SAL
    FROM EMP
    WHERE JOB IN ('SALESMAN')
    GROUP BY DEPTNO,SAL;
    SELECT DEPTNO , COUNT(JOB)
    FROM EMP
    WHERE JOB IN ('MANAGER', 'CLERK')
    GROUP BY DEPTNO
    HAVING COUNT(*) >2;
    SELECT JOB,SAL, COUNT(*)
    FROM EMP
    WHERE SAL > =3000
    GROUP BY JOB,SAL
    HAVING MIN(SAL) <= 5000
    ORDER BY SAL,JOB ASC;
    SELECT DEPTNO,JOB, COUNT(*)
    FROM EMP
    WHERE JOB IN ('CLERK')
    GROUP BY DEPTNO, JOB
    HAVING COUNT(*) > =2;
    SELECT JOB, COUNT(*),SUM(SAL)
    FROM EMP
    WHERE SAL > 1200
    GROUP BY JOB 
    HAVING SUM(SAL) >= 1300;
    SELECT ENAME ,SAL
    FROM EMP
    WHERE LENGTH(SAL) =3;
    SELECT SAL, COUNT(*)
    FROM EMP
    GROUP BY SAL
    HAVING COUNT(*) <=1;
    SELECT LENGTH(ENAME), ENAME,JOB
    FROM EMP
    WHERE JOB = 'MANAGER';
    SELECT CONCAT('DIWAKAR', 'K')
    , LOWER('DIWAKAR'),UPPER('diwakark')
    FROM DUAL;
    SELECT INITCAP('kDIWAKAR')
    FROM DUAL;
    SELECT REVERSE(ENAME),ENAME FROM EMP;
    SELECT *
    FROM EMP
    WHERE SUBSTR(ENAME, 1,2) ='AL';
    SELECT *
    FROM EMP
    WHERE INSTR(ENAME, 'A', 1, 2) >= 29;
    SELECT ename, sal from emp
    where sal >(SELECT sal from emp 
    where ename = 'MILLER');
    select sal,job, ename 
    from emp;
    select ename , sal ,job
    from emp
    where job IN (select job from 
    emp where ename = 'SMITH');
    select sal , ename 
    from emp 
    where sal > (select sal FROM
    emp where ENAME = 'MILLER') AND sal < (select sal from
    emp where ENAME = 'KING');
    select ename,sal 
    from emp
    where sal >=(select sal from emp where ENAME = 'BLAKE');
    select MGR ,ENAME ,sal*12 as annual_salary
    from EMP
    where MGR =(SELECT EMPNO FROM EMP 
    WHERE ENAME = 'BLAKE');
    SELECT * FROM EMP;
    SELECT ENAME
    FROM EMP
    WHERE ENAME LIKE '%A%A%';
    SELECT ENAME 
    FROM EMP;
    SELECT ENAME
    FROM EMP
    WHERE HIREDATE LIKE '%81';
select * FROM emp
WHERE sal > ALL (SELECT sal 
FROM emp WHERE JOB = 'MANAGER');
SELECT * FROM emp
WHERE HIREDATE > ALL (SELECT HIREDATE
FROM emp WHERE JOB = 'CLERK');
SELECT * FROM EMP
WHERE SAL >ALL (SELECT SAL
FROM EMP WHERE
ENAME = 'MILLER') AND HIREDATE > ALL
(SELECT HIREDATE
FROM EMP WHERE JOB = 'ANALYST');
SELECT LOC FROM
DEPT WHERE DEPTNO = (SELECT DEPTNO 
FROM EMP WHERE EMPNO = (SELECT MGR 
FROM EMP WHERE ENAME = 'JAMES'));
SELECT ENAME FROM EMP
WHERE MGR = (SELECT EMPNO FROM EMP
WHERE ENAME = 'KING'); 
SELECT LOC FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO FROM
EMP WHERE MGR =(SELECT EMPNO FROM EMP
WHERE ENAME = 'FORD'));
SELECT * FROM DEPT;
SELECT E1.EMPNO,M1.EMPNO 
FROM EMP E1,EMP M1
WHERE E1.EMPNO = M1.MGR;
SELECT * from EMP , DEPT;
SELECT * FROM EMP , DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;
SELECT ENAME , SAL ,JOB,LOC FROM
EMP , DEPT WHERE EMP.DEPTNO = DEPT.DEPTNO
AND SAL > 1000 AND LOC = 'NEW YORK';
SELECT * FROM EMP NATURAL JOIN DEPT;
select * from emp e, DEPT d 
where e.DEPTNO(+) = d.DEPTNO;
SELECT E.ENAME, E.HIREDATE, E1.ENAME,E1.HIREDATE
FROM EMP E, EMP E1
WHERE E.EMPNO = E1.MGR AND E.HIREDATE > '31-DEC-1981' AND E1.COMM IS NULL;
SELECT * FROM EMP E1
WHERE EXISTS (
  SELECT 1 FROM EMP E2
  WHERE E1.SAL = E2.SAL AND E1.EMPNO <> E2.EMPNO
);
SELECT SAL, COUNT(*)
FROM EMP
GROUP BY SAL 
HAVING COUNT(*) > 1;
